version: '3'
services:
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: REDIS_URL="redis://redis:6379/0" bundle exec sidekiq
    volumes:
      - .:/app
    env_file:
      - .env
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    volumes:
      - .:/app

volumes:
  dbdata:
